-- 코드를 입력하세요
SELECT SUBSTRING(DATETIME,12,2) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE SUBSTRING(DATETIME,12,2) BETWEEN 09 AND 20
GROUP BY SUBSTRING(DATETIME,12,2)
ORDER BY SUBSTRING(DATETIME,12,2)